### ISSUE TITLE
Tracking issue for contribution guide as code

### ISSUE THREAD

**Issue by tisonkun** [oceanbase/oceanbase#1386]
This supersedes https://github.com/oceanbase/oceanbase/issues/1338.

## Motivation

Currently, we have a series of contribution guides:

* https://github.com/oceanbase/oceanbase/wiki/Compile
* https://github.com/oceanbase/oceanbase/wiki/Set_IDE
* https://github.com/oceanbase/oceanbase/wiki/Deploy
* https://github.com/oceanbase/oceanbase/wiki/Deploy_with_Docker
* https://github.com/oceanbase/oceanbase/wiki/Debug
* https://github.com/oceanbase/oceanbase/wiki/Test
* https://github.com/oceanbase/oceanbase/wiki/Contribute-to-OceanBase

... while they are all impressive content, using Wiki prevents collaboration in PRs.

Besides, these pages somewhat lack cross-links, so, as mentioned in https://github.com/oceanbase/oceanbase/issues/1338#issuecomment-1499253229, the developer experience is fragmented.

## Proposal

As resolved in https://github.com/oceanbase/oceanbase/issues/1338#issuecomment-1519292414, we agree on:

1. Move contribution guides under VCS control. Concretely, create a `docs` folder to hold dev guides.
2. Fix or improve the content on the fly.

## Subtasks

* [ ] Create the `docs` folder and update README for documentation info
* [ ] Move the Compile guide to the `docs` folder
* [ ] Move the IDE Setup guide to the `docs` folder
* [ ] Move the Deploy guide to the `docs` folder
* [ ] Move the Deploy with Docker guide to the `docs` folder
* [ ] Move the Debug guide to the `docs` folder
* [ ] Move the Test guide to the `docs` folder
* [ ] Move the Contribute to OceanBase guide to the `docs` folder

**Comment by caifeizhi** [comment]
Thank you for your suggestion. Additionally, I suggest that some of the articles can be merged and adjusted to a certain extent, not necessarily following the original format.
